### ISSUE TITLE
Add QRL - Quantum Resistant Ledger to the list

### ISSUE THREAD

**Issue by kernelpanik23** [markf94/os_quantum_software#13]
As title requests please add to your list QRL - Quantum Resistant Ledger

[https://theqrl.org](url)

**Comment by markf94** [comment]
I've thought about this for a bit since its tangential to the core mission of this project. However, I think it fits nicely into the `Quantum cryptography` section alongside the quantum-proof OpenSSH and OpenSSL projects.

Thanks for your input!
